name: Test package

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test-code:
    name: Test on ${{ matrix.label }}
    runs-on: ubuntu-24.04
    container: ghcr.io/fenics/dolfinx/dolfinx:${{ matrix.label }}
    env:
      DEB_PYTHON_INSTALL_LAYOUT: deb_system
      OMPI_ALLOW_RUN_AS_ROOT: 1
      OMPI_ALLOW_RUN_AS_ROOT_CONFIRM: 1
      PRTE_MCA_rmaps_default_mapping_policy: :oversubscribe
    strategy:
      fail-fast: false
      matrix:
        label: ["nightly", "stable", "v0.10.0"]

    steps:
      - uses: actions/checkout@v7

      - name: Update pip
        run: python3 -m pip install --upgrade pip

      - name: Install package
        run: python3 -m pip install ".[test]"

      - name: Run tests (serial)
        run: python3 -m pytest -v

      - name: Run tests (parallel)
        run: mpirun -n 2 python3 -m pytest -v -m "not serial"
